# SPDX-License-Identifier: MIT

"""
This module contains the NoisyDeepESDv2 model for statistical downscaling.

NoisyDeepESDv2 extends DeepESDv2 with stochastic noise injection in the encoder,
following the implementation in Lang et al. (2024). The noise is injected via
Conditional Layer Normalization (CLN) in each transformer encoder block. The
cross-attention decoder is unchanged — noise-conditioned encoder tokens propagate
stochasticity to the output through cross-attention.

Lang, S., Alexe, M., Clare, M. C., Roberts, C., Adewoyin, R., Bouallègue, Z. B., ... & Leutbecher, M. (2024).
AIFS-CRPS: ensemble forecasting using a model trained with a loss function based on the continuous ranked
probability score. arXiv preprint arXiv:2412.15832.

Authors:
    Jose González-Abad
"""

from typing import Optional

import torch
import torch.nn as nn

from ..vit.blocks import NoiseEmbedding, TransformerBlockCLN
from .blocks import (CrossAttentionDecoderBlock, LocalCrossAttentionDecoderBlock,
                      NeRFPositionalEncoding)


class NoisyDeepESDv2(nn.Module):
    """
    Noisy DeepESDv2: Vision Transformer encoder with noise injection and
    cross-attention decoder for stochastic statistical downscaling.

    Identical to DeepESDv2 except the encoder uses TransformerBlockCLN blocks
    conditioned on sampled noise via Conditional Layer Normalization (CLN). At
    training time, multiple ensemble members are generated by sampling different
    noise realizations. At inference time, a single member is returned.

    The decoder uses query embeddings of dimension ``query_dim`` that are
    projected to the encoder dimension through the Q weight matrix of the
    cross-attention mechanism. Two query-embedding modes are supported:

    * **Learnable (default):** one free ``nn.Parameter`` per output grid point,
      used when ``grid_coords`` is ``None``.
    * **NeRF positional encoding:** multi-frequency sinusoidal encoding
      (Mildenhall et al., ECCV 2020) that evaluates sin/cos at geometrically
      increasing frequencies, producing highly discriminative embeddings even
      for spatially close grid points. Activated by passing ``grid_coords``.
      A linear projection maps the raw features to ``query_dim``.

    When ``local_indices`` is provided the decoder uses local cross-attention:
    each query attends only to a precomputed subset of K encoder tokens instead
    of all of them, reducing cost from O(N_out * N_enc) to O(N_out * K).

    Static covariables (e.g. orography, land-sea mask) that live on the
    predictand grid can be injected via ``covariables``.  Each covariable is
    independently projected to ``covar_embed_dim`` dimensions by a learned
    linear layer shared across grid points, following the standard approach
    used in GraphCast (Lam et al., Science 2023) and GenCast (Price et al.,
    Nature 2024) for static surface features.  The resulting embeddings are
    concatenated to the decoder queries before the first cross-attention
    block, so that the cross-attention mechanism can condition on the local
    surface properties of each output grid point.

    Lang, S., Alexe, M., Clare, M. C., Roberts, C., Adewoyin, R., Bouallègue, Z. B., ... & Leutbecher, M. (2024).
    AIFS-CRPS: ensemble forecasting using a model trained with a loss function based on the continuous ranked
    probability score. arXiv preprint arXiv:2412.15832.

    Parameters
    ----------
    x_shape : tuple
        Shape of the input data. Must be 4D: (batch, channels, height, width).
        The spatial dimensions must be divisible by patch_size.

    n_out : int
        Number of output grid points.

    patch_size : int
        Size of the patches extracted from the input for building token embeddings.
        Must divide both spatial dimensions of the input.

    dim : int
        Embedding dimension for the encoder. Must be divisible by num_heads.

    depth : int
        Number of transformer encoder blocks.

    num_heads : int
        Number of attention heads in transformer and cross-attention blocks.

    mlp_dim : int
        Hidden dimension of the MLP in the encoder transformer blocks and, when
        the decoder applies a post-cross-attention MLP, of that MLP as well.

    decoder_depth : int
        Number of cross-attention decoder blocks.

    noise_channels : int
        Number of noise channels injected per token. Must be greater than 0.

    noise_dim : int
        Dimension of the noise embeddings produced by NoiseEmbedding.

    query_dim : int
        Dimension of the decoder query embeddings. Used by the learnable mode
        and as the output projection dimension in the NeRF mode.

    local_indices : torch.Tensor or None, optional
        Long tensor of shape ``(n_out, K)`` mapping each query to K encoder
        tokens for local cross-attention. When None (default), standard global
        cross-attention is used.

    decoder_cross_attn_mlp : bool or None, optional
        Whether each decoder block applies a feedforward MLP after cross-attention.
        If ``None`` (default), the global cross-attention decoder omits this MLP
        (historical behavior), while local decoders include it. If ``True`` or
        ``False``, that choice applies to all decoder block types.

    grid_coords : torch.Tensor or None, optional
        Float tensor of shape ``(n_out, coord_dim)`` with the spatial coordinates
        of each output grid point. Coordinates should be pre-normalized to a
        suitable range (e.g. ``[-1, 1]``) before being passed; the model stores
        and uses them as-is. When provided, NeRF positional encoding is used for
        the decoder queries; when ``None`` (default), learnable embeddings are
        used instead.

    nerf_num_frequencies : int, optional
        Number of frequency octaves for the NeRF encoding. Only used when
        ``grid_coords`` or ``encoder_grid_coords`` is provided. Default is 10.

    encoder_grid_coords : torch.Tensor or None, optional
        Float tensor of shape ``(num_patches, coord_dim)`` with the spatial
        coordinates of each encoder patch center. When provided, NeRF
        positional encoding replaces the learnable encoder position
        embeddings. When ``None`` (default), learnable embeddings are used.

    share_nerf_encoding : bool, optional
        If True and both ``grid_coords`` and ``encoder_grid_coords`` are
        provided, the encoder and decoder share the same
        ``NeRFPositionalEncoding`` module (including its learnable linear
        projection). This requires ``dim == query_dim``. Default is False.

    covariables : torch.Tensor or None, optional
        Float tensor of shape ``(n_out, n_covars)`` with static covariable
        values for each output grid point (e.g. orography, land-sea mask).
        Covariables should be pre-normalized to a suitable range (e.g.
        ``[-1, 1]``) before being passed.  Each covariable column is embedded
        independently by a learned ``Linear(1, covar_embed_dim)`` layer shared
        across grid points.  The embeddings are concatenated to the decoder
        queries.  When ``None`` (default), no covariables are used.

    covar_embed_dim : int, optional
        Embedding dimension produced by each covariable projection layer.
        Only used when ``covariables`` is provided. Default is 16.

    members_for_training : int, optional
        Number of ensemble members to generate during training (each with an
        independent noise sample). Default is 2.

    num_vars : int, optional
        Number of output variables. The output shape is always (B, N_out, num_vars).
        Default is 1.

    dropout : float, optional
        Dropout probability. Default is 0.0.

    last_relu : bool, optional
        If True, applies ReLU to the final output. Default is False.
    """

    def __init__(self, x_shape, n_out, patch_size, dim, depth, num_heads,
                 mlp_dim, decoder_depth, noise_channels, noise_dim, query_dim,
                 local_indices=None,
                 decoder_cross_attn_mlp: Optional[bool] = None,
                 grid_coords=None, nerf_num_frequencies=10,
                 encoder_grid_coords=None, share_nerf_encoding=False,
                 covariables=None, covar_embed_dim=16,
                 members_for_training=2, num_vars=1,
                 dropout=0., last_relu=False):
        super().__init__()

        if len(x_shape) != 4:
            raise ValueError('x_shape must be 4D (B, C, H, W)')

        if x_shape[2] % patch_size != 0 or x_shape[3] % patch_size != 0:
            raise ValueError('Input spatial dimensions must be divisible by patch_size')

        self.noise_channels = noise_channels
        self.members_for_training = members_for_training
        self.last_relu = last_relu
        self.num_vars = num_vars

        self.num_patches = (x_shape[2] // patch_size) * (x_shape[3] // patch_size)

        # ENCODER

        self.patch_embedding = nn.Conv2d(x_shape[1], dim,
                                         kernel_size=patch_size, stride=patch_size)

        self.share_nerf_encoding = share_nerf_encoding and encoder_grid_coords is not None

        if encoder_grid_coords is not None:
            if encoder_grid_coords.shape[0] != self.num_patches:
                raise ValueError('encoder_grid_coords first dim must equal num_patches')
            self.register_buffer('encoder_grid_coords', encoder_grid_coords)
            self.pos_embedding = None
            if self.share_nerf_encoding:
                if grid_coords is None:
                    raise ValueError('share_nerf_encoding requires grid_coords (decoder NeRF)')
                if dim != query_dim:
                    raise ValueError('share_nerf_encoding requires dim == query_dim')
            else:
                self.encoder_pos_encoder = NeRFPositionalEncoding(
                    encoder_grid_coords.shape[1], nerf_num_frequencies, output_dim=dim)
        else:
            self.encoder_grid_coords = None
            self.pos_embedding = nn.Parameter(torch.empty(1, self.num_patches, dim))
            nn.init.trunc_normal_(self.pos_embedding, std=0.02)

        self.dropout_emb = nn.Dropout(dropout)

        self.noise_embedding = NoiseEmbedding(noise_channels, noise_dim)

        self.transformer_blocks = nn.ModuleList([
            TransformerBlockCLN(dim, num_heads, mlp_dim, noise_dim, dropout)
            for _ in range(depth)
        ])
        self.encoder_norm = nn.LayerNorm(dim)

        # DECODER

        self.use_local_attention = local_indices is not None
        if self.use_local_attention:
            self.register_buffer('local_indices', local_indices)
            attn_mask = torch.ones(n_out, self.num_patches, dtype=torch.bool)
            attn_mask.scatter_(1, local_indices, False)
            self.register_buffer('local_attn_mask', attn_mask)

        if grid_coords is not None:
            if grid_coords.shape[0] != n_out:
                raise ValueError('grid_coords first dim must equal n_out')
            self.register_buffer('grid_coords', grid_coords)
            self.query_encoder = NeRFPositionalEncoding(
                grid_coords.shape[1], nerf_num_frequencies, output_dim=query_dim)
            self.query_embedding = None
            effective_query_dim = self.query_encoder.output_dim
        else:
            self.grid_coords = None
            self.query_encoder = None
            self.query_embedding = nn.Parameter(torch.empty(1, n_out, query_dim))
            nn.init.trunc_normal_(self.query_embedding, std=0.02)
            effective_query_dim = query_dim

        # COVARIABLE EMBEDDINGS

        self.has_covariables = covariables is not None
        if self.has_covariables:
            if covariables.shape[0] != n_out:
                raise ValueError('covariables first dim must equal n_out')
            self.register_buffer('covariables', covariables)
            n_covars = covariables.shape[1]
            self.covar_embeddings = nn.ModuleList([
                nn.Linear(1, covar_embed_dim) for _ in range(n_covars)
            ])
            effective_query_dim += n_covars * covar_embed_dim

        # Validate that effective query dimension equals encoder dimension (kv_dim)
        # This is required for residual connections in the first decoder block.
        # Without this, query identity is lost at initialization.
        if effective_query_dim != dim:
            raise ValueError(f'effective_query_dim ({effective_query_dim}) must equal dim ({dim}) '
                             f'for cross-attention decoder with residual connections. '
                             f'Adjust query_dim, covar_embed_dim, or number of covariables. '
                             f'Query components: query_dim={query_dim}, '
                             f'covar_embed_dim={covar_embed_dim}, n_covars={n_covars if self.has_covariables else 0}')

        if self.use_local_attention:
            DecoderBlock = LocalCrossAttentionDecoderBlock
        else:
            DecoderBlock = CrossAttentionDecoderBlock

        if decoder_cross_attn_mlp is None:
            use_cross_attn_mlp = (DecoderBlock is not CrossAttentionDecoderBlock)
        else:
            use_cross_attn_mlp = decoder_cross_attn_mlp

        decoder_blocks = []
        for i in range(decoder_depth):
            q_dim = effective_query_dim if i == 0 else dim
            decoder_blocks.append(DecoderBlock(
                q_dim, dim, num_heads, mlp_dim, dropout,
                use_cross_attn_mlp=use_cross_attn_mlp))
        self.decoder_blocks = nn.ModuleList(decoder_blocks)
        self.decoder_norm = nn.LayerNorm(dim)

        self.output_head = nn.Linear(dim, num_vars)

    def _encode(self, x, z):
        """
        Run the encoder for one noise sample.

        Parameters
        ----------
        x : Tensor
            Input batch of shape ``(B, C, H, W)``.

        z : Tensor
            Noise embedding tensor of shape ``(B, N_patches, noise_dim)`` produced
            by ``NoiseEmbedding``.

        Returns
        -------
        Tensor
            Encoder tokens of shape ``(B, N_enc, dim)``.
        """
        tokens = self.patch_embedding(x)
        tokens = tokens.flatten(2).transpose(1, 2)

        if self.encoder_grid_coords is not None:
            enc = self.query_encoder if self.share_nerf_encoding else self.encoder_pos_encoder
            tokens = tokens + enc(self.encoder_grid_coords).unsqueeze(0)
        else:
            tokens = tokens + self.pos_embedding
        tokens = self.dropout_emb(tokens)
        for block in self.transformer_blocks:
            tokens = block(tokens, z)
        return self.encoder_norm(tokens)   # (B, N_enc, dim)

    def _decode(self, encoder_tokens):
        """
        Run the decoder given encoder tokens.

        Parameters
        ----------
        encoder_tokens : Tensor
            Encoder output of shape ``(B, N_enc, dim)``.

        Returns
        -------
        Tensor
            Predictions of shape ``(B, n_out, num_vars)``.
        """
        B = encoder_tokens.shape[0]

        if self.query_embedding is not None:
            queries = self.query_embedding.expand(B, -1, -1)       # (B, N_out, query_dim)
        else:
            queries = self.query_encoder(self.grid_coords)         # (N_out, query_dim)
            queries = queries.unsqueeze(0).expand(B, -1, -1)       # (B, N_out, query_dim)

        if self.has_covariables:
            covar_embs = [fc(self.covariables[:, i:i+1])
                          for i, fc in enumerate(self.covar_embeddings)]
            covar_emb = torch.cat(covar_embs, dim=-1).unsqueeze(0).expand(B, -1, -1)
            queries = torch.cat([queries, covar_emb], dim=-1)

        for block in self.decoder_blocks:
            if self.use_local_attention:
                queries = block(queries, encoder_tokens, self.local_attn_mask)
            else:
                queries = block(queries, encoder_tokens)
        queries = self.decoder_norm(queries)               # (B, N_out, dim)

        out = self.output_head(queries)                    # (B, N_out, num_vars)

        if self.last_relu:
            out = torch.relu(out)

        if self.num_vars == 1:
            out = out.squeeze(-1)                          # (B, N_out)

        return out

    def forward(self, x):
        """
        Parameters
        ----------
        x : Tensor
            Input batch of shape ``(B, C, H, W)`` matching ``x_shape``.

        Returns
        -------
        Tensor or list of Tensor
            With gradient enabled or in training mode: a list of length
            ``members_for_training``, each tensor of shape ``(B, n_out, num_vars)``.
            In inference mode without gradients: a single tensor of shape
            ``(B, n_out, num_vars)``.
        """
        B = x.shape[0]

        is_ensemble_mode = self.training or torch.is_grad_enabled()
        members_to_iterate = self.members_for_training if is_ensemble_mode else 1

        out_members = []
        for _ in range(members_to_iterate):
            z = torch.randn(B, self.num_patches, self.noise_channels, device=x.device)
            z = self.noise_embedding(z)

            encoder_tokens = self._encode(x, z)
            out_members.append(self._decode(encoder_tokens))

        if is_ensemble_mode:
            return out_members   # list of (B, N_out, num_vars)
        else:
            return out_members[0]   # (B, N_out, num_vars)
